server:
  port: 9090
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9092
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: stock-service
          uri: http://localhost:9093
          predicates:
            - Path=/stock/**
          filters:
            - StripPrefix=1
        - id: basket-service
          uri: http://localhost:9091
          predicates:
            - Path=/basket/**
          filters:
            - StripPrefix=1