server:
  port: 9090
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://127.0.0.1:9092
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: stock-service
          uri: http://127.0.0.1:9093
          predicates:
            - Path=/stock/**
          filters:
            - StripPrefix=1
        - id: basket-service
          uri: http://127.0.0.1:9091
          predicates:
            - Path=/basket/**
          filters:
            - StripPrefix=1
        - id: invoice-service
          uri: http://127.0.0.1:9094
          predicates:
            - Path=/invoice/**
          filters:
            - StripPrefix=1
        - id: notification-service
          uri: http://127.0.0.1:9095
          predicates:
            - Path=/notification/**
          filters:
            - StripPrefix=1